/opt/litmus-tests-riscv/tests/non-mixed-size/HAND/MP+fence.rw.rw+rmw-wsi-rfi-addr.litmus	No	Ok
/opt/litmus-tests-riscv/tests/non-mixed-size/HAND/SWAP-LR-SC+FULL.litmus	No	Ok
/opt/litmus-tests-riscv/tests/non-mixed-size/HAND/ISA11+BIS.litmus	No	Ok
/opt/litmus-tests-riscv/tests/non-mixed-size/ATOMICS/CO/WRC+fence.rw.rwspx+fence.rw.rwsxp.litmus	Ok	No
/opt/litmus-tests-riscv/tests/non-mixed-size/ATOMICS/CO/RWC+pospx+fence.rw.rwsxp.litmus	Ok	No
/opt/litmus-tests-riscv/tests/non-mixed-size/ATOMICS/CO/WWC+fence.rw.rwsxx+posxp+X.litmus	Ok	No
/opt/litmus-tests-riscv/tests/non-mixed-size/ATOMICS/CO/RWC+fence.rw.rwspx+fence.rw.rwsxp.litmus	Ok	No
/opt/litmus-tests-riscv/tests/non-mixed-size/AMO_X0_2_THREAD/S+po+poarp+NEW.litmus	No	Ok
/opt/litmus-tests-riscv/tests/non-mixed-size/AMO_X0_2_THREAD/SB+po+popar+NEW.litmus	No	Ok
