tests/non-mixed-size/AMO_X0_2_THREAD/2+2W+po+popar+NEW.json	Ok	Ok
tests/non-mixed-size/AMO_X0_2_THREAD/MP+poarar+po+NEW.json	Ok	Ok
tests/non-mixed-size/AMO_X0_2_THREAD/MP+poarar+popar+NEW.json	No	No
tests/non-mixed-size/AMO_X0_2_THREAD/R+poarars+NEW.json	No	No
tests/non-mixed-size/AMO_X0_2_THREAD/R+poarp+poarar+NEW.json	No	No
tests/non-mixed-size/AMO_X0_2_THREAD/R+popar+poarar+NEW.json	No	No
tests/non-mixed-size/AMO_X0_2_THREAD/S+po+poarp+NEW.json	No	Ok
tests/non-mixed-size/AMO_X0_2_THREAD/S+poprl+po+NEW.json	Ok	Ok
tests/non-mixed-size/AMO_X0_2_THREAD/SB+po+popar+NEW.json	No	Ok
tests/non-mixed-size/AMO_X0_2_THREAD/SB+popar+poarar+NEW.json	No	No
tests/non-mixed-size/ATOMICS/CO/2+2W+fence.rw.rwsxp+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoRR+fence.rw.rws+X.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoRR+fence.rw.rwsxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoRW1+posxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoRW2+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoRW2+posxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/CoWR0+posxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/LB+fence.rw.rwspx+fence.rw.rwsxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/LB+fence.rw.rwspx+posxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/LB+pos+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/MP+fence.rw.rwspx+fence.rw.rwsxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/MP+fence.rw.rwsxp+pos.json	No	No
tests/non-mixed-size/ATOMICS/CO/MP+pos+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/MP+pos+posxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/MP+pospx+fence.rw.rwsxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+fence.rw.rws+fence.rw.rwspx.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+fence.rw.rws+fence.rw.rwsxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+fence.rw.rws+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+pos+posxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+posxp+fence.rw.rws.json	No	No
tests/non-mixed-size/ATOMICS/CO/R+posxx+pos.json	No	No
tests/non-mixed-size/ATOMICS/CO/RWC+fence.rw.rws+pospx+X.json	No	No
tests/non-mixed-size/ATOMICS/CO/RWC+fence.rw.rws+posxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/RWC+fence.rw.rwspx+fence.rw.rwsxp.json	Ok	No
tests/non-mixed-size/ATOMICS/CO/RWC+pospx+fence.rw.rwsxp.json	Ok	No
tests/non-mixed-size/ATOMICS/CO/S+fence.rw.rwsxp+fence.rw.rws.json	No	No
tests/non-mixed-size/ATOMICS/CO/S+fence.rw.rwsxp+fence.rw.rwspx.json	No	No
tests/non-mixed-size/ATOMICS/CO/SB+fence.rw.rws+fence.rw.rwspx.json	No	No
tests/non-mixed-size/ATOMICS/CO/SB+fence.rw.rws+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/SB+fence.rw.rwsxxs.json	No	No
tests/non-mixed-size/ATOMICS/CO/SB+posxps.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRC+fence.rw.rws+posxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRC+fence.rw.rwspx+fence.rw.rwsxp.json	Ok	No
tests/non-mixed-size/ATOMICS/CO/WRC+pos+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRC+posxp+fence.rw.rws.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRC+posxp+fence.rw.rwsxp.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRR+2W+fence.rw.rws+pos+X.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRR+2W+fence.rw.rws+posxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRW+2W+pos+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRW+2W+pos+posxx.json	No	No
tests/non-mixed-size/ATOMICS/CO/WRW+WR+pos+pospx.json	No	No
tests/non-mixed-size/ATOMICS/CO/WWC+fence.rw.rwss+X.json	No	No
tests/non-mixed-size/ATOMICS/CO/WWC+fence.rw.rwsxp+fence.rw.rws+X.json	No	No
tests/non-mixed-size/ATOMICS/CO/WWC+fence.rw.rwsxx+posxp+X.json	Ok	No
tests/non-mixed-size/ATOMICS/CO/WWC+pospx+fence.rw.rws.json	No	No
tests/non-mixed-size/ATOMICS/RELAX/PodRWXP/LB+data+poxp.json	Ok	Ok
tests/non-mixed-size/BASIC_2_THREAD/2+2W.json	Ok	Ok
tests/non-mixed-size/BASIC_2_THREAD/LB+ctrl+po.json	Ok	Ok
tests/non-mixed-size/BASIC_2_THREAD/LB+data+ctrl.json	No	No
tests/non-mixed-size/CO/2+2W+poss.json	No	No
tests/non-mixed-size/CO/CoWW+fence.rw.rws.json	No	No
tests/non-mixed-size/CO/MP+fence.rw.rws+pos.json	No	No
tests/non-mixed-size/CO/WRR+2W+fence.rw.rws+pos.json	No	No
tests/non-mixed-size/CO/WRW+WR+pos+fence.rw.rws.json	No	No
tests/non-mixed-size/FENCE.TSO/2/LB+fence.tsopxs.json	No	No
tests/non-mixed-size/FENCE.TSO/2/MP+fence.tsopx+fence.tsoxp.json	No	No
tests/non-mixed-size/FENCE.TSO/2/MP+fence.tsoxp+fence.tsopx.json	No	No
tests/non-mixed-size/FENCE.TSO/2/MP+fence.tsoxx+fence.tsopx.json	No	No
tests/non-mixed-size/FENCE.TSO/2/R+fence.tso+fence.tsopx.json	No	No
tests/non-mixed-size/FENCE.TSO/2/S+fence.tsoxp+fence.tsoxx.json	No	No
tests/non-mixed-size/HAND/2+2W+fence.w.w+fence.tso.json	Ok	Ok
tests/non-mixed-size/HAND/Andy27.json	No	No
tests/non-mixed-size/HAND/ISA-DEP-ADDR.json	Ok	Ok
tests/non-mixed-size/HAND/ISA01.json	Ok	Ok
tests/non-mixed-size/HAND/ISA11+BIS.json	No	Ok
tests/non-mixed-size/HAND/LB+amoadd-data-amoadd.rl+amoadd.aq-data-amoadd.json	No	No
tests/non-mixed-size/HAND/Luc03.json	No	No
tests/non-mixed-size/HAND/MP+fence.rw.rw+rmw-wsi-rfi-addr.json	No	Ok
tests/non-mixed-size/HAND/RSW+W.json	No	No
tests/non-mixed-size/HAND/SWAP-LR-SC+FULL.json	No	Ok
tests/non-mixed-size/RELAX/Coi-Rfi/S+fence.rw.rw+addr-wsi-rfi-ctrl.json	No	No
tests/non-mixed-size/RELAX/Fence.idRW/LB+fence.is.json	Ok	Ok
tests/non-mixed-size/RELAX/Fence.r.rwdWW/MP+fence.r.rws.json	Ok	Ok
tests/non-mixed-size/RELAX/Fence.r.rwdWW/S+fence.r.rw+data.json	Ok	Ok
tests/non-mixed-size/RELAX/Fence.w.wdRW/LB+fence.w.w+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Fence.w.wdRW/LB+fence.w.ws.json	Ok	Ok
tests/non-mixed-size/RELAX/Fri-Rfi/LB+addr+ctrl-fri-rfi-ctrl.json	No	No
tests/non-mixed-size/RELAX/Fri-Rfi/LB+ctrl+addr-fri-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Fri-Rfi/LB+data+ctrl-fri-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Fri-Rfi/LB+data+fri-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/Fri-Rfi/MP+fence.rw.rw+fri-rfi-addr-fri-rfi.json	Ok	Ok
tests/non-mixed-size/RELAX/Fri-Rfi/S+fence.rw.rw+fri-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/R+fence.w.w+po.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/SB+fence.rw.rw+po-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/SB+fence.rw.rw+po-ctrlfenceis.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/SB+fence.rw.rw+pos-po.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/SB+po+po-addrs.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWR/SB+po-addrs+po-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/PodWW/S+po+fence.rw.w.json	Ok	Ok
tests/non-mixed-size/RELAX/PosWR/R+fence.rw.w+pos-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/PosWR/SB+pos-ctrlfencei+pos-pos-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/2+2W+fence.rw.w+rfi-ctrl.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/2+2W+rfi-ctrlfenceis.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/LB+addr+ctrlfencei-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+addr-rfi-ctrl+data-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+addr-rfi-ctrlfencei+ctrl-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+addr-rfi-data+ctrlfencei-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrl+data-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrl-rfi-addr+ctrlfencei-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrl-rfi-ctrl+ctrl-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrl-rfi-ctrl+ctrlfencei-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrl-rfi-data+ctrlfencei-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrlfencei+ctrl-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrlfencei+ctrlfencei-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+ctrlfencei-rfi-ctrlfenceis.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+data+ctrl-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+data-rfi-addr+ctrlfencei-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+data-rfi-ctrl+ctrlfencei-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+data-rfi-ctrlfenceis.json	No	No
tests/non-mixed-size/RELAX/Rfi/LB+fence.rw.w+addr-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/MP+fence.rw.rw+addr-rfi-addrs.json	No	No
tests/non-mixed-size/RELAX/Rfi/MP+fence.w.w+addr-rfi-ctrlfenceis.json	No	No
tests/non-mixed-size/RELAX/Rfi/MP+fence.w.w+addr-rfi.json	No	No
tests/non-mixed-size/RELAX/Rfi/MP+fence.w.w+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+pos-rfi-addr+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+pos-rfi-ctrlfencei+addr-rfi-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+pos-rfi-ctrlfencei+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+pos-rfi-ctrlfencei+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-addr+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-addr+ctrlfencei-rfi.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-addr+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-ctrl+ctrlfencei-rfi-addrs.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-ctrlfencei+ctrlfencei-rfi-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-data+addr-rfi-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-data+data-rfi.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/MP+rfi-data+fence.r.rw.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/R+pos-rfi-ctrl+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/R+pos-rfi-ctrlfencei+rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/R+rfi-addr+rfi-ctrlfencei-rfi.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+fence.rw.rw+addr-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Rfi/S+fence.rw.rw+ctrlfencei-rfi-ctrlfencei.json	No	No
tests/non-mixed-size/RELAX/Rfi/S+fence.rw.w+ctrlfencei-rfi-addr.json	No	No
tests/non-mixed-size/RELAX/Rfi/S+fence.w.w+addr-rfi-data.json	No	No
tests/non-mixed-size/RELAX/Rfi/S+rfi-addr+ctrlfencei-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-ctrl+ctrl-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-ctrl+data-rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-ctrl+data-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-ctrlfencei+ctrl-rfi-data.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-data+ctrl-rfi-addr.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/S+rfi-data+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/SB+rfi-addr+rfi-ctrlfencei.json	Ok	Ok
tests/non-mixed-size/RELAX/Rfi/SB+rfi-data-rfis.json	Ok	Ok
tests/non-mixed-size/SAFE/2+2W+fence.rw.w+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/3.2W+fence.w.w+fence.rw.w+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/3.LB+addr+ctrlfencei+ctrl.json	No	No
tests/non-mixed-size/SAFE/3.LB+addr+data+ctrl.json	No	No
tests/non-mixed-size/SAFE/3.LB+addrs.json	No	No
tests/non-mixed-size/SAFE/3.LB+ctrlfenceis.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.r.rw+ctrl+addr.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.r.rw+ctrlfencei+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.r.rw+data+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.r.rws.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.rw+addr+pos.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.rw+ctrl+ctrl.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.rw+ctrl+pos.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.rw+data+ctrl.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.w+ctrl+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.w+data+addr.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.w+data+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/3.LB+fence.rw.w+fence.rw.rw+ctrl.json	No	No
tests/non-mixed-size/SAFE/IRIW+addr+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/IRIW+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/IRRWIW+addr+ctrl.json	No	No
tests/non-mixed-size/SAFE/IRRWIW+fence.r.rw+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/IRRWIW+fence.rw.rw+addr.json	No	No
tests/non-mixed-size/SAFE/IRRWIW+fence.rw.rw+fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/IRWIW+datas.json	No	No
tests/non-mixed-size/SAFE/IRWIW+fence.rw.rw+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/IRWIW+fence.rw.w+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.rw.rw+data+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/ISA2+fence.rw.rw+fence.r.rw+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.rw.w+ctrl+addrs.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.rw.w+data+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/ISA2+fence.rw.w+fence.r.rw+addrs.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.w.w+ctrlfencei+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.w.w+fence.r.rw+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/ISA2+fence.w.w+fence.rw.w+fence.r.rws.json	No	No
tests/non-mixed-size/SAFE/ISA2+fence.w.w+pos+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/ISA2+pos+data+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/ISA2+pos+data+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/LB+[fr-fence.rw.rw-ws]+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/LB+[fr-rf]-ctrlfencei+ctrl.json	No	No
tests/non-mixed-size/SAFE/LB+[fr-rf]-data+data.json	No	No
tests/non-mixed-size/SAFE/LB+[fr-rf]-fence.rw.rw+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/LB+addr+addr-[fr-ws].json	No	No
tests/non-mixed-size/SAFE/LB+addr+addr-[rf-fr].json	No	No
tests/non-mixed-size/SAFE/LB+fence.r.rw+ctrlfencei-[fr-ws].json	No	No
tests/non-mixed-size/SAFE/LB+fence.r.rw+ctrlfencei-[rf-fr].json	No	No
tests/non-mixed-size/SAFE/MP+[rf-ctrl-ws]+fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/MP+[rf-fence.rw.rw-ws]+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/MP+[rf-fr]-fence.rw.w+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/MP+[ws-fence.rw.w-ws]+addr.json	No	No
tests/non-mixed-size/SAFE/MP+[ws-fence.w.w-ws]+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/MP+[ws-rf]-ctrl+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/MP+fence.rw.rw+fence.r.rw-[fr-rf].json	No	No
tests/non-mixed-size/SAFE/MP+fence.rw.rw-[fr-ws]+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/MP+fence.rw.w+[fr-fence.rw.rw-rf].json	No	No
tests/non-mixed-size/SAFE/MP+fence.rw.w+fence.rw.rw-[fr-rf].json	No	No
tests/non-mixed-size/SAFE/MP+fence.w.w+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/MP+fence.w.w-[rf-fr]+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/R+[ws-rf]-addr+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/R+fence.rw.rw+[rf-fence.r.rw-rf].json	No	No
tests/non-mixed-size/SAFE/R+fence.w.w+[rf-fence.rw.rw-rf].json	No	No
tests/non-mixed-size/SAFE/S+[rf-ctrlfencei-fr]+data.json	Ok	Ok
tests/non-mixed-size/SAFE/S+[rf-ctrlfencei-ws]+fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/S+[rf-fence.rw.rw-ws]+fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/S+[rf-fence.rw.w-ws]+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/S+fence.rw.rw+[fr-rf]-fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/S+fence.rw.rw+[fr-rf]-fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/S+fence.rw.w+ctrl.json	No	No
tests/non-mixed-size/SAFE/S+fence.rw.w-[rf-fr]+ctrl.json	No	No
tests/non-mixed-size/SAFE/S+fence.w.w+[fr-fence.rw.rw-fr].json	No	No
tests/non-mixed-size/SAFE/S+fence.w.w+[fr-rf]-fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/S+fence.w.w+ctrl.json	No	No
tests/non-mixed-size/SAFE/W+RWC+fence.rw.rw+fence.r.rw+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/W+RWC+fence.rw.w+ctrlfencei+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/SAFE/W+RWC+fence.rw.w+ctrlfenceis+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/W+RWC+fence.rw.w+fence.rw.rw+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/W+RWC+fence.w.w+fence.r.rws+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/WRC+ctrlfencei+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/WRC+fence.rw.rw+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/WRC+fence.rw.w+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/WRW+2W+fence.r.rw+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/WRW+WR+data+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/WWC+ctrl+addr.json	No	No
tests/non-mixed-size/SAFE/WWC+fence.rw.rw+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.rw.rw+fence.r.rw+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.w.w+addr+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.w.w+ctrl+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.w.w+fence.rw.rw+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.0+fence.w.w+fence.rw.w+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.0+pos+data+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.1+fence.rw.rw+fence.w.w+ctrlfencei.json	No	No
tests/non-mixed-size/SAFE/Z6.1+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/Z6.1+fence.rw.w+fence.rw.rw+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.1+fence.rw.w+fence.w.w+ctrl.json	No	No
tests/non-mixed-size/SAFE/Z6.1+fence.w.w+fence.w.w+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+addr+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+ctrl+addr.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+fence.r.rw+ctrl.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+fence.r.rw+fence.r.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+fence.rw.rw+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+fence.rw.w+addr.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.rw+fence.rw.w+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.rw.w+ctrlfencei+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.w.w+ctrl+fence.rw.w.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.w.w+ctrlfencei+addr.json	No	No
tests/non-mixed-size/SAFE/Z6.2+fence.w.w+data+fence.rw.rw.json	No	No
tests/non-mixed-size/SAFE/Z6.3+fence.rw.rw+fence.rw.w+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SAFE/Z6.3+fence.rw.w+fence.rw.rw+addr.json	No	No
tests/non-mixed-size/SAFE/Z6.3+fence.rw.w+fence.rw.w+addrs.json	No	No
tests/non-mixed-size/SAFE/Z6.3+fence.rw.w+fence.rw.w+fence.rw.rws.json	No	No
tests/non-mixed-size/SAFE/Z6.3+fence.w.w+fence.w.w+addr.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/2+2W+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+addr+data+data.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+ctrlfencei+po+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+datas.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+fence.rw.rw+ctrl+ctrl.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+fence.rw.rw+fence.rw.rw+ctrl.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/3.LB+fence.rw.rw+po+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/ISA2+fence.rw.rw+ctrl+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/ISA2+po+addr+addr.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/ISA2+po+data+addr.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/ISA2+po+fence.rw.rw+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/LB+addr+ctrlfencei.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/MP.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/RWC+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/SB.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/W+RWC+fence.rw.rw+ctrl+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/W+RWC+fence.rw.rws.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/WRC+addr+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/WRC+ctrlfencei+fence.rw.rw.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/WRC+ctrlfenceis.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/WRC+fence.rw.rws.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/WRC+po+ctrlfencei.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/WRR+2W+ctrlfencei+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/WRW+WR+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/WWC+ctrlfencei+data.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/Z6.0+fence.rw.rw+ctrlfencei+fence.rw.rw.json	No	No
tests/non-mixed-size/SF_THESIS/BASIC/Z6.0+po+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.0.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.1+po+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.2+po+addr+ctrl.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.2+po+ctrl+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.2+po+ctrlfencei+data.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.4+po+po+fence.rw.rw.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.5+fence.rw.rw+po+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/BASIC/Z6.5+po+fence.rw.rw+po.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/CO/CO-SBI.json	Ok	Ok
tests/non-mixed-size/SF_THESIS/CO/MP+fence.rw.rws+pos.json	No	No
tests/non-mixed-size/SF_THESIS/CO/R+poss.json	No	No
tests/non-mixed-size/SF_THESIS/CO/WRC+fence.rw.rws+pos.json	No	No
tests/non-mixed-size/SF_THESIS/CO/WRC+pos+fence.rw.rws.json	No	No
tests/non-mixed-size/SF_THESIS/CO/WRR+2W+poss.json	No	No
tests/non-mixed-size/SF_THESIS/HAND/PPOAA.json	No	No
tests/non-mixed-size/SF_THESIS/HAND/RDW.json	No	No
tests/non-mixed-size/SF_THESIS/HAND/SB+rfi-addrs.json	Ok	Ok
tests/to-AArch64/RV+2+2W+fence.r.rws.json	Ok	Ok
tests/to-AArch64/RV+2+2W+fence.w.w+rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+2+2W+rfi-addrs.json	Ok	Ok
tests/to-AArch64/RV+2+2W+rfi-ctrlfenceis.json	Ok	Ok
tests/to-AArch64/RV+3.LB+addr+addr+pos.json	No	No
tests/to-AArch64/RV+3.LB+ctrl+ctrlfencei+pos.json	Ok	No
tests/to-AArch64/RV+3.LB+data+ctrl+pos.json	Ok	No
tests/to-AArch64/RV+3.LB+fence.r.rw+data+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+3.LB+fence.r.rw+fence.rw.rw+pos.json	No	No
tests/to-AArch64/RV+3.LB+fence.rw.rw+addr+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+3.LB+fence.rw.rw+data+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+3.LB+fence.rw.rw+fence.rw.rw+data.json	No	No
tests/to-AArch64/RV+IRRWIW+addr+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+IRRWIW+addr+data.json	No	No
tests/to-AArch64/RV+IRRWIW+addr+fence.rw.rw.json	No	No
tests/to-AArch64/RV+IRRWIW+fence.rw.rw+addr.json	No	No
tests/to-AArch64/RV+IRWIW+addr+ctrl.json	Ok	No
tests/to-AArch64/RV+IRWIW+fence.r.rw+data.json	No	No
tests/to-AArch64/RV+ISA14.json	Ok	Ok
tests/to-AArch64/RV+ISA2+fence.rw.rw+ctrl+addrs.json	Ok	No
tests/to-AArch64/RV+ISA2+fence.rw.rw+ctrlfencei+ctrlfenceis.json	Ok	No
tests/to-AArch64/RV+ISA2+fence.rw.rw+data+ctrlfenceis.json	No	No
tests/to-AArch64/RV+ISA2+fence.w.w+ctrlfencei+addrs.json	Ok	No
tests/to-AArch64/RV+ISA2+fence.w.w+ctrlfencei+fence.rw.rws.json	Ok	No
tests/to-AArch64/RV+ISA2+fence.w.w+fence.r.rw+fence.rw.rws.json	No	No
tests/to-AArch64/RV+ISA2+fence.w.w+fence.rw.rw+fence.r.rw.json	No	No
tests/to-AArch64/RV+ISA2+fence.w.w+fence.rw.rw+fence.rw.rws.json	No	No
tests/to-AArch64/RV+ISA2+pos+data+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+ISA2+pos+data+fence.rw.rw.json	No	No
tests/to-AArch64/RV+LB+[fr-fence.rw.rw-fr]+addr.json	No	No
tests/to-AArch64/RV+LB+[fr-fence.rw.rw-fr]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+[fr-fence.rw.rw-ws]+addr.json	No	No
tests/to-AArch64/RV+LB+[fr-fence.rw.rw-ws]+data.json	No	No
tests/to-AArch64/RV+LB+[fr-fence.w.w-ws]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+[fr-rf]-addr+fence.r.rw.json	No	No
tests/to-AArch64/RV+LB+[fr-rf]-ctrl+fence.rw.rw.json	Ok	No
tests/to-AArch64/RV+LB+[fr-rf]-ctrlfencei+ctrl.json	Ok	No
tests/to-AArch64/RV+LB+[fr-rf]-data+data.json	No	No
tests/to-AArch64/RV+LB+[fr-rf]-fence.r.rw+ctrl.json	Ok	No
tests/to-AArch64/RV+LB+addr+addr-fri-rfi-ctrl.json	No	No
tests/to-AArch64/RV+LB+addr+addr-wsi-rfi-addr.json	No	No
tests/to-AArch64/RV+LB+addr+data-wsi-rfi-ctrl.json	Ok	Ok
tests/to-AArch64/RV+LB+addr-[fr-ws]+ctrl.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-addr+ctrlfencei-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-addr+data-rfi-data.json	No	No
tests/to-AArch64/RV+LB+addr-rfi-ctrl+ctrl-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-ctrl+ctrlfencei-rfi-ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-ctrl+data-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-data+addr-rfi-ctrl.json	No	No
tests/to-AArch64/RV+LB+addr-rfi-data+ctrl-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+LB+addr-rfi-data+ctrl-rfi-data.json	Ok	No
tests/to-AArch64/RV+LB+ctrl+addr-fri-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+ctrl+po.json	Ok	Ok
tests/to-AArch64/RV+LB+ctrl+popx.json	No	Ok
tests/to-AArch64/RV+LB+ctrl-rfi-addr+ctrl-rfi-data.json	Ok	No
tests/to-AArch64/RV+LB+ctrl-rfi-addr+ctrlfencei-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+ctrl-rfi-data+ctrlfencei-rfi-ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+data+ctrl-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+data+ctrl-wsi-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+data+data-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+LB+data+po.json	Ok	Ok
tests/to-AArch64/RV+LB+data-[rf-fr]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+fence.i+fence.rw.rw.json	Ok	Ok
tests/to-AArch64/RV+LB+fence.r.rw+addr-[fr-ws].json	No	No
tests/to-AArch64/RV+LB+fence.r.rw+addr-rfi-ctrlfencei.json	No	No
tests/to-AArch64/RV+LB+fence.r.rw+addr-rfi-data.json	No	No
tests/to-AArch64/RV+LB+fence.r.rw+ctrl.json	Ok	No
tests/to-AArch64/RV+LB+fence.r.rw+ctrlfencei-[fr-ws].json	Ok	No
tests/to-AArch64/RV+LB+fence.r.rw+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+fence.r.rw+data-po.json	Ok	Ok
tests/to-AArch64/RV+LB+fence.r.rw+data-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+LB+fence.r.rw+data-rfi-data.json	No	No
tests/to-AArch64/RV+LB+fence.rw.rw+addr-fri-rfi-ctrl.json	No	No
tests/to-AArch64/RV+LB+fence.rw.rw+addr-rfi-addr.json	No	No
tests/to-AArch64/RV+LB+fence.rw.rw+ctrl-rfi-addr.json	Ok	No
tests/to-AArch64/RV+LB+fence.rw.rw+data-wsi-rfi-ctrl.json	Ok	Ok
tests/to-AArch64/RV+LB+fence.rw.rw+fence.rw.rw-[rf-fr].json	No	No
tests/to-AArch64/RV+LB+fence.rw.rw-[fr-ws]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+LB+fence.w.w+fence.rw.rw.json	Ok	Ok
tests/to-AArch64/RV+LB+fri-rfi-addr+fri-rfi-data.json	Ok	Ok
tests/to-AArch64/RV+MP+[rf-ctrlfencei-fr]+addr.json	Ok	No
tests/to-AArch64/RV+MP+[rf-fence.r.rw-ws]+addr.json	No	No
tests/to-AArch64/RV+MP+[rf-fence.rw.rw-fr]+addr.json	No	No
tests/to-AArch64/RV+MP+[rf-fr]-fence.w.w+fence.rw.rw.json	No	No
tests/to-AArch64/RV+MP+[ws-fence.rw.rw-ws]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+MP+[ws-rf]-data+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+MP+fence.rw.rw+addr.json	No	No
tests/to-AArch64/RV+MP+fence.rw.rw+ctrl-fri-rfi.json	Ok	No
tests/to-AArch64/RV+MP+fence.rw.rw+ctrl-rfi.json	Ok	No
tests/to-AArch64/RV+MP+fence.rw.rw+ctrlfencei-rfi.json	Ok	No
tests/to-AArch64/RV+MP+fence.rw.rw+data-rfi-ctrlfencei.json	Ok	No
tests/to-AArch64/RV+MP+fence.rw.rws.json	No	No
tests/to-AArch64/RV+MP+fence.w.w+[fr-rf]-addr.json	No	No
tests/to-AArch64/RV+MP+fence.w.w+[fr-rf]-ctrlfencei.json	Ok	No
tests/to-AArch64/RV+MP+fence.w.w+[fr-rf]-fence.r.rw.json	No	No
tests/to-AArch64/RV+MP+fence.w.w+addr-rfi-addr.json	No	No
tests/to-AArch64/RV+MP+fence.w.w+ctrlfencei-rfi-ctrlfenceis.json	Ok	No
tests/to-AArch64/RV+MP+po+ctrl.json	Ok	Ok
tests/to-AArch64/RV+MP+pos-rfi-addr+data-rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+MP+pos-rfi-addr+fence.r.rw.json	Ok	Ok
tests/to-AArch64/RV+MP+pos-rfi-data+ctrl-rfi-addr.json	Ok	Ok
tests/to-AArch64/RV+MP+rfi-ctrl+data-rfi-ctrlfenceis.json	Ok	Ok
tests/to-AArch64/RV+MP+rfi-ctrlfencei+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+MP+rfi-data+ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+MP+rfi-data+data-rfi.json	Ok	Ok
tests/to-AArch64/RV+R+[rf-addr-fr]+fence.rw.rw.json	No	No
tests/to-AArch64/RV+R+[ws-rf]-ctrl+fence.rw.rw.json	Ok	No
tests/to-AArch64/RV+R+fence.rw.rw+[rf-ctrlfencei-rf].json	Ok	No
tests/to-AArch64/RV+R+fence.w.w+[rf-ctrl-rf].json	Ok	No
tests/to-AArch64/RV+R+fence.w.w+[rf-data-rf].json	No	No
tests/to-AArch64/RV+R+fence.w.w+rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+R+po+fence.rw.rw.json	Ok	Ok
tests/to-AArch64/RV+R+rfi-data+rfi-addr.json	Ok	Ok
tests/to-AArch64/RV+RWC+addr+fence.rw.rw.json	No	No
tests/to-AArch64/RV+S+[rf-addr-ws]+addr.json	No	No
tests/to-AArch64/RV+S+[rf-addr-ws]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+S+[rf-data-ws]+fence.rw.rw.json	No	No
tests/to-AArch64/RV+S+[rf-fence.r.rw-fr]+addr.json	No	No
tests/to-AArch64/RV+S+[rf-fence.r.rw-ws]+fence.rw.rw.json	No	No
tests/to-AArch64/RV+S+[rf-fence.rw.rw-ws]+data.json	No	No
tests/to-AArch64/RV+S+fence.i+data.json	Ok	Ok
tests/to-AArch64/RV+S+fence.r.rw+addr.json	Ok	Ok
tests/to-AArch64/RV+S+fence.r.rw+ctrl.json	Ok	Ok
tests/to-AArch64/RV+S+fence.rw.rw+addr-fri-rfi-addr.json	No	No
tests/to-AArch64/RV+S+fence.rw.rw+addr-rfi-addr.json	No	No
tests/to-AArch64/RV+S+fence.rw.rw+addr-wsi-rfi-ctrl.json	No	No
tests/to-AArch64/RV+S+fence.rw.rw+ctrl-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+S+fence.rw.rw+ctrl.json	Ok	No
tests/to-AArch64/RV+S+fence.rw.rw+ctrlfencei-rfi-ctrl.json	Ok	No
tests/to-AArch64/RV+S+fence.rw.rw+poxp.json	No	Ok
tests/to-AArch64/RV+S+fence.rw.rw-[fr-ws]+ctrl.json	Ok	No
tests/to-AArch64/RV+S+fence.rw.rw-[fr-ws]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+S+fence.rw.rw-[rf-fr]+ctrl.json	Ok	No
tests/to-AArch64/RV+S+fence.w.w+ctrl-rfi-ctrlfencei.json	Ok	No
tests/to-AArch64/RV+S+fence.w.w+data-rfi-data.json	No	No
tests/to-AArch64/RV+S+fence.w.w+data.json	No	No
tests/to-AArch64/RV+S+fence.w.w-[rf-fr]+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+S+po+data.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-addr+ctrlfencei-rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-ctrl+data-rfi-addr.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-ctrl+data.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-ctrlfencei+addr.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-ctrlfencei+ctrlfencei-rfi-addr.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-ctrlfencei+ctrlfencei-rfi-ctrl.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-data+addr-rfi-ctrl.json	Ok	Ok
tests/to-AArch64/RV+S+rfi-data+data-rfi-ctrl.json	Ok	Ok
tests/to-AArch64/RV+SB+[rf-fr]-fence.rw.rw+fence.rw.rw.json	No	No
tests/to-AArch64/RV+SB+fence.rw.rw+po.json	Ok	Ok
tests/to-AArch64/RV+SB+fence.rw.rw+pos-pos-addr.json	Ok	Ok
tests/to-AArch64/RV+SB+fence.rw.rw+pos-rfi-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+SB+po-ctrlfenceis+pos-po-addr.json	Ok	Ok
tests/to-AArch64/RV+SB+po-ctrlfenceis+pos-po-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-ctrlfencei+pos-pos-addr.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-ctrlfenceis.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po+pos-po-addr.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po+pos-po-addrs.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po+pos-po-ctrlfenceis.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po-addrs+pos-po-ctrlfenceis.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po-addrs.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po-addrss.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-po-ctrlfenceis+pos-po-ctrlfencei.json	Ok	Ok
tests/to-AArch64/RV+SB+pos-pos-addrs.json	Ok	Ok
tests/to-AArch64/RV+SB+rfi-addr+pos-rfi-addr.json	Ok	Ok
tests/to-AArch64/RV+SB+rfi-addr+rfi-addr-rfi.json	Ok	Ok
tests/to-AArch64/RV+SB+rfi-addr-rfi+rfi-ctrlfencei-rfi.json	Ok	Ok
tests/to-AArch64/RV+W+RWC+fence.rw.rw+fence.r.rws+fence.rw.rw.json	No	No
tests/to-AArch64/RV+W+RWC+fence.w.w+addr+fence.rw.rws.json	No	No
tests/to-AArch64/RV+W+RWC+pos+addr+fence.rw.rw.json	No	No
tests/to-AArch64/RV+WRC+ctrlfencei+fence.r.rw.json	Ok	No
tests/to-AArch64/RV+WRC+fence.rw.rws.json	No	No
tests/to-AArch64/RV+WRR+2W+ctrlfencei+fence.w.w.json	Ok	No
tests/to-AArch64/RV+WRW+2W+fence.rw.rws.json	No	No
tests/to-AArch64/RV+WRW+WR+fence.r.rw+fence.rw.rw.json	No	No
tests/to-AArch64/RV+WWC+ctrl+fence.r.rw.json	Ok	No
tests/to-AArch64/RV+WWC+ctrlfencei+addr.json	Ok	No
tests/to-AArch64/RV+WWC+data+addr.json	No	No
tests/to-AArch64/RV+WWC+data+ctrl.json	Ok	No
tests/to-AArch64/RV+WWC+fence.rw.rw+addr.json	No	No
tests/to-AArch64/RV+WWC+fence.rw.rws.json	No	No
tests/to-AArch64/RV+Z6.0+pos+fence.r.rw+fence.rw.rw.json	No	No
tests/to-AArch64/RV+Z6.2+fence.rw.rw+data+data.json	No	No
tests/to-AArch64/RV+Z6.2+fence.rw.rw+fence.r.rw+ctrl.json	Ok	No
tests/to-AArch64/RV+Z6.2+fence.rw.rw+fence.rw.rw+addr.json	No	No
tests/to-AArch64/RV+Z6.2+fence.w.w+addr+addr.json	No	No
tests/to-AArch64/RV+Z6.2+fence.w.w+addr+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+Z6.2+fence.w.w+addr+fence.r.rw.json	No	No
tests/to-AArch64/RV+Z6.2+fence.w.w+ctrl+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+Z6.2+fence.w.w+pos+addr.json	No	No
tests/to-AArch64/RV+Z6.2+fence.w.w+pos+ctrl.json	Ok	No
tests/to-AArch64/RV+Z6.3+fence.w.w+fence.rw.rw+ctrlfencei.json	Ok	No
tests/to-AArch64/RV+Z6.3+fence.w.w+fence.w.w+addrs.json	No	No
tests/to-AArch64/RV+Z6.4+fence.w.w+fence.rw.rw+fence.rw.rw.json	No	No
