name: CI Build

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  HOLBA_OPT_DIR: /home/runner/cache
  HOLBA_BOT_GITHUB_TOKEN: 'comment. see scripts/ci/post-comment-on-PR.sh, use github actions secrets'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        polyml: ['v5.7.1', 'v5.9']
        z3: ['4.8.4']
        hol4: ['kananaskis-14']

    env:
      HOLBA_POLYML_VERSION: ${{ matrix.polyml }}
      HOLBA_Z3_VERSION: ${{ matrix.z3 }}
      HOLBA_Z3_ASSET_SUFFIX: '.d6df51951f4c-x64-debian-8.11.zip'
      HOLBA_HOL4_VERSION: ${{ matrix.hol4 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.HOLBA_OPT_DIR }}
          key: os-${{ runner.os }}_polyml-${{ matrix.polyml }}_z3-${{ matrix.z3 }}_hol4-${{ matrix.hol4 }}

      - name: Static analysis
        timeout-minutes: 5
        run: |
          ./scripts/ci/static-analysis.sh || echo "Static-analysis failed with status $?."

      - name: Prepare cached dependencies
        timeout-minutes: 35
        run: |
          ./scripts/setup/install_base.sh
          ./scripts/setup/install_z3.sh

      - name: Configure and compile
        timeout-minutes: 35
        run: |
          ./configure.sh
          ./scripts/ci/run_holmake.sh

      - name: Run tests
        timeout-minutes: 35
        run: |
          ./scripts/ci/run_make.sh tests


